export const BALANCE = {
  clock: {
    dayDurationSeconds: 90,
    recoveryTickSeconds: 1,
    maxFrameDeltaSeconds: 0.06,
  },
  movement: {
    speedByFaction: {
      blue: 0.045,
      red: 0.035,
      gray: 0.035,
      pink: 0.035,
    },
    routeSnapDistance: 0.008,
    unitSelectionRadius: 0.055,
    dispatchDragDistance: 0.012,
  },
  units: {
    baseMaxStrengthByFaction: {
      blue: 18,
      red: 12,
      gray: 12,
      pink: 12,
    },
    minimumSurvivorStrength: 1,
  },
  territoryProduction: {
    "kr-42": 2,
    "kr-41": 3,
    "kr-44": 2,
    "kr-28": 2,
    "kr-45": 2,
    "kr-46": 2,
    "kr-48": 2,
    "kr-26": 2,
    "kr-31": 2,
    "kr-47": 2,
    "kr-49": 1,
    "kr-11": 3,
    "kr-30": 2,
    "kr-50": 2,
    "kr-43": 2,
    "kr-29": 2,
    "kr-27": 2,
    "kp-07": 1,
    "kp-06": 1,
    "kp-09": 1,
    "kp-13": 1,
    "kp-10": 1,
    "kp-04": 1,
    "kp-03": 1,
    "kp-02": 2,
    "kp-05": 1,
    "kp-08": 1,
    "kp-01": 2,
  },
  occupation: {
    durationSeconds: 5,
  },
  combat: {
    contactDistance: 0.055,
    tickIntervalSeconds: 0.72,
    initialTickDelaySeconds: 0.2,
    strengthDamageFactor: 0.1,
    productionDamageFactor: 0.6,
    minimumDamage: 2,
  },
  specialMove: {
    usesPerOperation: 3,
    maxNameLength: 24,
    types: {
      enemyWeakness: {
        defaultName: "敵弱体化",
        strengthReductionRate: 0.2,
      },
      allyBoost: {
        defaultName: "味方強化",
        strengthIncreaseRate: 0.2,
      },
      invincibility: {
        defaultName: "無敵",
        durationSeconds: 3,
      },
    },
  },
  ai: {
    initialDelaySeconds: 3.2,
    actionDelaySeconds: 3.8,
    actionDelayJitterSeconds: 2.6,
    invasionWarningSeconds: 5,
    activeUnitLimit: 5,
    reinforcementLimit: 5,
  },
  campaign: {
    frontTypes: {
      regionalSmall: { targetDurationSeconds: 330, phaseCount: 1 },
      regionalLarge: { targetDurationSeconds: 540, phaseCount: 2 },
      major: { targetDurationSeconds: 420, phaseCount: 2 },
      worldCoalition: { targetDurationSeconds: 540, phaseCount: 3 },
      finalForce: { targetDurationSeconds: 570, phaseCount: 3 },
    },
    enemyProfiles: {
      regionalIntro: { strengthMultiplier: 0.85, activeUnitLimit: 3, reinforcementLimit: 2, actionDelaySeconds: 4.8 },
      regionalEarly: { strengthMultiplier: 0.95, activeUnitLimit: 4, reinforcementLimit: 3, actionDelaySeconds: 4.4 },
      regionalLate: { strengthMultiplier: 1.05, activeUnitLimit: 5, reinforcementLimit: 4, actionDelaySeconds: 4.0 },
      majorEarly: { strengthMultiplier: 1.15, activeUnitLimit: 5, reinforcementLimit: 5, actionDelaySeconds: 3.8 },
      majorMiddle: { strengthMultiplier: 1.25, activeUnitLimit: 6, reinforcementLimit: 6, actionDelaySeconds: 3.5 },
      majorLate: { strengthMultiplier: 1.35, activeUnitLimit: 6, reinforcementLimit: 7, actionDelaySeconds: 3.2 },
      worldCoalition: { strengthMultiplier: 1.5, activeUnitLimit: 7, reinforcementLimit: 8, actionDelaySeconds: 3.0 },
      finalForce: { strengthMultiplier: 1.65, activeUnitLimit: 8, reinforcementLimit: 10, actionDelaySeconds: 2.8 },
    },
  },
  targeting: {
    productionWeight: 0.35,
    factionPenalty: {
      blue: 0,
      gray: 0,
      pink: 2,
      red: 4,
    },
  },
  economy: {
    rewards: {
      captureGold: 15,
      battleWinGold: 10,
      defeatConversionRate: 0.35,
      defeatRewardCap: 60,
      minimumDefeatGold: 20,
      minimumDefeatElapsedSeconds: 30,
      minimumDefeatCaptures: 1,
      clearBonus: 50,
      campaignClearBonus: 300,
    },
    upgradePriceGrowth: 1.45,
    upgradePriceStep: 10,
    upgradePriceCap: 999999,
    shopItems: {
      logistics: { basePrice: 100, label: "回復力", productionPerLevel: 1 },
      armor: { basePrice: 100, label: "戦力", maxStrengthPerLevel: 3 },
      reserve: { basePrice: 150, label: "開始人数", unitsPerLevel: 1 },
      speed: { basePrice: 120, label: "速度アップ", speedPerLevel: 0.003 },
    },
  },
};
