export const COUNTRIES = {
  russia: {
    id: "russia",
    name: "Russia",
    shortName: "RUS",
    fragmentIds: ["russia-east", "russia-far-east"],
    isMajor: true,
    description: "A major country represented by multiple geographic fragments.",
    flag: { type: "horizontal", colors: ["#ffffff", "#2455a4", "#d52b1e"] },
  },
  kazakhstan: {
    id: "kazakhstan",
    name: "Kazakhstan",
    shortName: "KAZ",
    fragmentIds: ["kazakhstan"],
    isMajor: false,
    description: "The western entry point of the East Asia front.",
    flag: { type: "field", colors: ["#00afca", "#f6d04d"] },
  },
  mongolia: {
    id: "mongolia",
    name: "Mongolia",
    shortName: "MNG",
    fragmentIds: ["mongolia"],
    isMajor: false,
    description: "A central land corridor between Russia and China.",
    flag: { type: "vertical", colors: ["#c4272f", "#164b9b", "#c4272f"] },
  },
  china: {
    id: "china",
    name: "China",
    shortName: "CHN",
    fragmentIds: ["china-north", "china-central", "china-south"],
    isMajor: true,
    description: "A major country whose control requires all three fragments.",
    flag: { type: "field", colors: ["#de2910", "#ffde00"] },
  },
  "north-korea": {
    id: "north-korea",
    name: "North Korea",
    shortName: "PRK",
    fragmentIds: ["north-central", "north-west", "north-hwanghae", "north-east-central", "north-east"],
    isMajor: false,
    description: "An enemy Korean Peninsula country split into five strategic regions.",
    flag: { type: "horizontal", colors: ["#024fa2", "#ffffff", "#ed1c27"] },
  },
  "south-korea": {
    id: "south-korea",
    name: "South Korea",
    shortName: "KOR",
    fragmentIds: ["south-capital", "south-gangwon", "south-central", "south-west", "south-east", "south-jeju"],
    isMajor: false,
    description: "An enemy Korean Peninsula country split into six strategic regions.",
    flag: { type: "field", colors: ["#ffffff", "#000000"] },
  },
  japan: {
    id: "japan",
    name: "Japan",
    shortName: "JPN",
    fragmentIds: ["japan"],
    isMajor: true,
    description: "A major island country reached through sea routes.",
    flag: { type: "field", colors: ["#ffffff", "#bc002d"] },
  },
  vietnam: {
    id: "vietnam",
    name: "Vietnam",
    shortName: "VNM",
    fragmentIds: ["vietnam"],
    isMajor: false,
    description: "A southern mainland fragment with a land route from China.",
    flag: { type: "field", colors: ["#da251d", "#ffcd00"] },
  },
  philippines: {
    id: "philippines",
    name: "Philippines",
    shortName: "PHL",
    fragmentIds: ["philippines"],
    isMajor: false,
    description: "An island country connected by sea routes.",
    flag: { type: "horizontal", colors: ["#0038a8", "#ce1126", "#ffffff"] },
  },
  indonesia: {
    id: "indonesia",
    name: "Indonesia",
    shortName: "IDN",
    fragmentIds: ["indonesia"],
    isMajor: false,
    description: "A southern island group at the end of the front.",
    flag: { type: "horizontal", colors: ["#ce1126", "#ffffff"] },
  },
};
