export const COUNTRIES = {
  russia: {
    id: "russia",
    name: "Russia",
    shortName: "RUS",
    fragmentIds: ["russia-east", "russia-far-east"],
    isMajor: true,
    description: "A major country represented by multiple geographic fragments.",
    flag: { type: "horizontal", colors: ["#ffffff", "#2455a4", "#d52b1e"] },
  },
  kazakhstan: {
    id: "kazakhstan",
    name: "Kazakhstan",
    shortName: "KAZ",
    fragmentIds: ["kazakhstan"],
    isMajor: false,
    description: "The western entry point of the East Asia front.",
    flag: { type: "field", colors: ["#00afca", "#f6d04d"] },
  },
  mongolia: {
    id: "mongolia",
    name: "Mongolia",
    shortName: "MNG",
    fragmentIds: ["mongolia"],
    isMajor: false,
    description: "A central land corridor between Russia and China.",
    flag: { type: "vertical", colors: ["#c4272f", "#164b9b", "#c4272f"] },
  },
  china: {
    id: "china",
    name: "China",
    shortName: "CHN",
    fragmentIds: ["china-north", "china-central", "china-south"],
    isMajor: true,
    description: "A major country whose control requires all three fragments.",
    flag: { type: "field", colors: ["#de2910", "#ffde00"] },
  },
  "north-korea": {
    id: "north-korea",
    name: "North Korea",
    shortName: "PRK",
    fragmentIds: [
      "kp-07",
      "kp-06",
      "kp-09",
      "kp-13",
      "kp-10",
      "kp-04",
      "kp-03",
      "kp-02",
      "kp-05",
      "kp-08",
      "kp-01",
    ],
    isMajor: false,
    description: "A Korean Peninsula country split into eleven first-order administrative fragments.",
    flag: { type: "horizontal", colors: ["#024fa2", "#ffffff", "#ed1c27"] },
  },
  "south-korea": {
    id: "south-korea",
    name: "South Korea",
    shortName: "KOR",
    fragmentIds: [
      "kr-42",
      "kr-41",
      "kr-44",
      "kr-28",
      "kr-45",
      "kr-46",
      "kr-48",
      "kr-26",
      "kr-31",
      "kr-47",
      "kr-49",
      "kr-11",
      "kr-30",
      "kr-50",
      "kr-43",
      "kr-29",
      "kr-27",
    ],
    isMajor: false,
    description: "A Korean Peninsula country split into seventeen first-order administrative fragments.",
    flag: { type: "field", colors: ["#ffffff", "#000000"] },
  },
  japan: {
    id: "japan",
    name: "Japan",
    shortName: "JPN",
    fragmentIds: ["japan"],
    isMajor: true,
    description: "A major island country reached through sea routes.",
    flag: { type: "field", colors: ["#ffffff", "#bc002d"] },
  },
  vietnam: {
    id: "vietnam",
    name: "Vietnam",
    shortName: "VNM",
    fragmentIds: ["vietnam"],
    isMajor: false,
    description: "A southern mainland fragment with a land route from China.",
    flag: { type: "field", colors: ["#da251d", "#ffcd00"] },
  },
  philippines: {
    id: "philippines",
    name: "Philippines",
    shortName: "PHL",
    fragmentIds: ["philippines"],
    isMajor: false,
    description: "An island country connected by sea routes.",
    flag: { type: "horizontal", colors: ["#0038a8", "#ce1126", "#ffffff"] },
  },
  indonesia: {
    id: "indonesia",
    name: "Indonesia",
    shortName: "IDN",
    fragmentIds: ["indonesia"],
    isMajor: false,
    description: "A southern island group at the end of the front.",
    flag: { type: "horizontal", colors: ["#ce1126", "#ffffff"] },
  },
};
