export const UNKNOWN_COUNTRY_FLAG_ORIGIN = "国旗の由来は不明。";

export function getCountryFlagOrigin(country) {
  return typeof country?.flagOrigin === "string" && country.flagOrigin.trim().length > 0
    ? country.flagOrigin
    : UNKNOWN_COUNTRY_FLAG_ORIGIN;
}

export const COUNTRIES = {
  russia: {
    id: "russia",
    name: "Russia",
    nameJa: "ロシア",
    shortName: "RUS",
    isoA3: "RUS",
    fragmentIds: ["russia-east", "russia-far-east"],
    isMajor: true,
    description: "A major country represented by multiple geographic fragments.",
    overview: "ロシアは東ヨーロッパから北アジアに広がる国です。国土はヨーロッパ側とアジア側の両方にまたがっています。",
    location: {
      region: "東ヨーロッパ・北アジア",
      description: "世界地図ではヨーロッパの東側から北アジアにかけて広がる位置にあります。",
    },
    flagOrigin: "現在の国旗は、白・青・赤の等しい幅の横三色旗です。ロシア連邦の公式資料で形と配色、縦横比2:3が定められています。色の解釈には複数の説明があるため、ここでは公式に確認できるデザインを紹介します。",
    trivia: [
      "バイカル湖はユネスコ世界遺産に登録されています。",
      "ロシアの国土はヨーロッパとアジアの両方にまたがっています。",
    ],
    sources: [
      { label: "ロシア連邦・国旗の公式説明", url: "https://www.gov.ru/main/symbols/gsrf3_1_en.html" },
      { label: "ロシア連邦統計局・統計年鑑", url: "https://eng.rosstat.gov.ru/storage/mediabank/Ejegodnik_2019%281%29.pdf" },
      { label: "ユネスコ・バイカル湖", url: "https://whc.unesco.org/en/list/754/" },
    ],
    flag: { type: "horizontal", colors: ["#ffffff", "#2455a4", "#d52b1e"] },
  },
  kazakhstan: {
    id: "kazakhstan",
    name: "Kazakhstan",
    nameJa: "カザフスタン",
    shortName: "KAZ",
    isoA3: "KAZ",
    fragmentIds: ["kazakhstan"],
    isMajor: false,
    description: "The western entry point of the East Asia front.",
    overview: "カザフスタンは中央アジアに位置する内陸国です。広い草原地帯を含み、ヨーロッパとアジアの接点に位置しています。",
    location: {
      region: "中央アジア",
      description: "世界地図ではロシアの南、カスピ海の東側にある広い内陸部に位置します。",
    },
    flagOrigin: "1992年に正式採用された国旗です。青地の中央に太陽と翼を広げたステップワシを置き、旗竿側に国民的な装飾文様を配しています。太陽・ワシ・文様は金色で描かれます。",
    trivia: [
      "北部のステップと湖沼を含むサリャルカは、ユネスコ世界遺産に登録されています。",
      "国旗のデザインは画家シャケン・ニヤズベコフによるものです。",
    ],
    sources: [
      { label: "カザフスタン政府・国のシンボル", url: "https://www.gov.kz/article/128915?lang=en" },
      { label: "カザフスタン政府・カザフスタン概要", url: "https://www.gov.kz/article/19305?lang=en" },
      { label: "ユネスコ・サリャルカ", url: "https://whc.unesco.org/en/list/1102" },
    ],
    flag: { type: "field", colors: ["#00afca", "#f6d04d"] },
  },
  mongolia: {
    id: "mongolia",
    name: "Mongolia",
    nameJa: "モンゴル",
    shortName: "MNG",
    isoA3: "MNG",
    fragmentIds: ["mongolia"],
    isMajor: false,
    description: "A central land corridor between Russia and China.",
    overview: "モンゴルはロシアと中国の間に位置する中央アジアの内陸国です。広い草原と乾燥した地域が見られます。",
    location: {
      region: "中央アジア",
      description: "世界地図ではロシアの南、中国の北にある内陸部に位置します。",
    },
    flagOrigin: "憲法で定められた国旗は、赤・青・赤の縦三分割です。旗竿側の赤い帯には金色のソヨンボを置き、中央の青は永遠の青空、左右の赤は発展と繁栄を表すと説明されています。縦横比は1:2です。",
    trivia: [
      "ナーダムは、モンゴル相撲・競馬・弓術を中心とする伝統行事です。",
      "ナーダムはユネスコ無形文化遺産に登録されています。",
    ],
    sources: [
      { label: "モンゴル憲法・国旗の規定", url: "https://conscourt.gov.mn/?lang=en&page_id=842" },
      { label: "モンゴル通信・国旗の説明", url: "https://montsame.mn/en/read/129473" },
      { label: "ユネスコ・ナーダム", url: "https://ich.unesco.org/en/RL/naadam-mongolian-traditional-festival-00395?lang=en" },
    ],
    flag: { type: "vertical", colors: ["#c4272f", "#164b9b", "#c4272f"] },
  },
  china: {
    id: "china",
    name: "China",
    nameJa: "中国",
    shortName: "CHN",
    isoA3: "CHN",
    fragmentIds: ["china-north", "china-central", "china-south"],
    isMajor: true,
    description: "A major country whose control requires all three fragments.",
    overview: "中国は東アジアに位置し、海岸部から内陸の高原・山地・砂漠まで多様な地形を持つ国です。",
    location: {
      region: "東アジア",
      description: "世界地図ではアジア大陸の東部にあり、東側が太平洋に面しています。",
    },
    flagOrigin: "国旗は赤地に五つの黄色い星を配したデザインです。中国の公式法令・政府資料で国旗の形と星の構成が定められています。",
    trivia: [
      "中国の伝統的な茶の製造技術と関連する社会的慣行は、ユネスコ無形文化遺産に登録されています。",
      "中国は海岸部から内陸部まで、地形の変化が大きい国です。",
    ],
    sources: [
      { label: "中国政府・憲法（国旗の規定）", url: "https://english.www.gov.cn/archive/law%25C2%25A0%25E2%2580%258Bsregulations/201911/20/content_WS5ed8856ec6d0b3f0e9499913.html" },
      { label: "中国最高人民法院・国旗法", url: "https://english.court.gov.cn/2016-04/14/c_1170197.htm" },
      { label: "ユネスコ・中国の茶文化", url: "https://ich.unesco.org/en/RL/traditional-tea-processing-techniques-and-associated-social-practices-in-china-01884?RL=01884" },
    ],
    flag: { type: "field", colors: ["#de2910", "#ffde00"] },
  },
  "north-korea": {
    id: "north-korea",
    name: "North Korea",
    nameJa: "北朝鮮",
    shortName: "PRK",
    isoA3: "PRK",
    fragmentIds: ["north-central", "north-west", "north-hwanghae", "north-east-central", "north-east"],
    isMajor: false,
    description: "An enemy Korean Peninsula country split into five strategic regions.",
    overview: "北朝鮮は朝鮮半島北部に位置する東アジアの国です。朝鮮半島には山地が多く、東側と西側で地形の特徴が異なります。",
    location: {
      region: "東アジア・朝鮮半島北部",
      description: "世界地図では朝鮮半島の北側にあり、西側が黄海、東側が日本海に面しています。",
    },
    flagOrigin: "国旗は中央の赤い帯を白い細帯と青い帯が上下から挟み、旗竿側の赤い円内に赤い五芒星を置く構成です。憲法資料では縦横比を1:2としています。ここでは確認できる形と配色を紹介します。",
    trivia: [
      "高句麗古墳群はユネスコ世界遺産に登録されています。",
      "朝鮮半島は東アジアの大陸部と海域の間にある半島です。",
    ],
    sources: [
      { label: "WIPO Lex・朝鮮民主主義人民共和国憲法", url: "https://www.wipo.int/wipolex/en/text/227797" },
      { label: "国連・DPR Korea 2008 Census", url: "https://dprkorea.un.org/sites/default/files/2019-07/Census-2008.pdf" },
      { label: "ユネスコ・高句麗古墳群", url: "https://whc.unesco.org/en/list/1091/" },
    ],
    flag: { type: "horizontal", colors: ["#024fa2", "#ffffff", "#ed1c27"] },
  },
  "south-korea": {
    id: "south-korea",
    name: "South Korea",
    nameJa: "韓国",
    shortName: "KOR",
    isoA3: "KOR",
    fragmentIds: ["south-capital", "south-gangwon", "south-central", "south-west", "south-east", "south-jeju"],
    isMajor: false,
    description: "An enemy Korean Peninsula country split into six strategic regions.",
    overview: "韓国は朝鮮半島南部に位置する東アジアの国です。国土の多くが山地で、東側に山地、西側に平野や干潟が広がります。",
    location: {
      region: "東アジア・朝鮮半島南部",
      description: "世界地図では朝鮮半島の南側にあり、三方を海に囲まれています。",
    },
    flagOrigin: "太極旗は白地の中央に赤と青の太極を置き、四隅に乾・坤・坎・離を表す四卦を配した国旗です。韓国の公式資料では1883年に国旗として採用されたと説明されています。",
    trivia: [
      "キムジャン（キムチを作り分け合う文化）は、ユネスコ無形文化遺産に登録されています。",
      "韓国の国花はムクゲです。",
    ],
    sources: [
      { label: "Korea.net・韓国概要と太極旗", url: "https://www.korea.net/AboutKorea/OverviewofKorea" },
      { label: "韓国行政安全部・太極旗", url: "https://www.mois.go.kr/eng/sub/a03/nationalSymbol/screen.do" },
      { label: "ユネスコ・キムジャン", url: "https://ich.unesco.org/en/RL/kimjang-making-and-sharing-kimchi-in-the-republic-of-korea-00881?RL=00881&lang=en" },
    ],
    flag: { type: "field", colors: ["#ffffff", "#000000"] },
  },
  japan: {
    id: "japan",
    name: "Japan",
    nameJa: "日本",
    shortName: "JPN",
    isoA3: "JPN",
    fragmentIds: [
      "japan-kyushu-north",
      "japan-kyushu-south",
      "japan-shikoku",
      "japan-chugoku",
      "japan-kansai",
      "japan-chubu",
      "japan-hokuriku",
      "japan-kanto",
      "japan-tohoku-south",
      "japan-tohoku-north",
      "japan-hokkaido",
    ],
    isMajor: true,
    description: "A major island country divided into eleven strategic regions.",
    overview: "日本は東アジアの島国で、北海道・本州・四国・九州などの島々から構成されています。",
    location: {
      region: "東アジア・西太平洋",
      description: "世界地図ではユーラシア大陸の東にあり、太平洋と日本海の間に弧状に並んでいます。",
    },
    flagOrigin: "日本の国旗は白地の中央に深い赤色の円を置くデザインで、日の丸・日章旗とも呼ばれます。政府の公式説明では、1999年の法律により国旗として正式化されました。",
    trivia: [
      "和食の伝統的な食文化は、ユネスコ無形文化遺産に登録されています。",
      "日本列島は北海道・本州・四国・九州を含む島々から成ります。",
    ],
    sources: [
      { label: "JapanGov・国旗と国歌", url: "https://www.japan.go.jp/japan/flagandanthem/index.html" },
      { label: "外務省・日本の領土", url: "https://www.mofa.go.jp/territory/page1we_000006.html" },
      { label: "ユネスコ・和食", url: "https://ich.unesco.org/en/RL/washoku-traditional-dietary-cultures-of-the-japanese-notably-for-the-celebration-of-new-year-00869" },
    ],
    flag: { type: "field", colors: ["#ffffff", "#bc002d"] },
  },
  vietnam: {
    id: "vietnam",
    name: "Vietnam",
    nameJa: "ベトナム",
    shortName: "VNM",
    isoA3: "VNM",
    fragmentIds: ["vietnam"],
    isMajor: false,
    description: "A southern mainland fragment with a land route from China.",
    overview: "ベトナムは東南アジアのインドシナ半島東側に位置する国です。北に中国、西にラオスとカンボジア、東に海があります。",
    location: {
      region: "東南アジア・インドシナ半島東部",
      description: "世界地図ではインドシナ半島の東側に細長く位置し、南シナ海に面しています。",
    },
    flagOrigin: "国旗は縦横比2:3の長方形で、赤地の中央に黄色い五芒星を置くデザインです。ベトナム政府ポータルの憲法掲載文で、この形と配色が定められています。",
    trivia: [
      "水上人形劇は、ベトナム北部に結び付いた伝統的な舞台芸術です。",
      "ベトナムには紅河デルタとメコンデルタという大きなデルタ地帯があります。",
    ],
    sources: [
      { label: "ベトナム政府・国旗の規定", url: "https://vietnam.gov.vn/national-flag-emblem-anthem-declaration-68960" },
      { label: "ベトナム外務省・地理", url: "https://www.mofa.gov.vn/en/tt_vietnam/geo/" },
      { label: "ベトナム政府観光局・水上人形劇", url: "https://vietnam.travel/things-to-do/vietnam-water-puppets" },
    ],
    flag: { type: "field", colors: ["#da251d", "#ffcd00"] },
  },
  philippines: {
    id: "philippines",
    name: "Philippines",
    nameJa: "フィリピン",
    shortName: "PHL",
    isoA3: "PHL",
    fragmentIds: ["philippines"],
    isMajor: false,
    description: "An island country connected by sea routes.",
    overview: "フィリピンは東南アジアの西太平洋にある群島国家です。ルソン、ビサヤ、ミンダナオの三つの大きな島嶼群に分けて説明されます。",
    location: {
      region: "東南アジア・西太平洋",
      description: "世界地図では台湾の南、インドネシアの北東にある島々として位置しています。",
    },
    flagOrigin: "国旗は青・白・赤を基調に、旗竿側の白い三角形へ八本の光条を持つ金色の太陽と三つの五芒星を配したデザインです。フィリピンの共和国法8491号で意匠が定められています。",
    trivia: [
      "フィリピン・コルディリェーラの棚田群は、ユネスコ世界遺産に登録されています。",
      "フィリピンはルソン、ビサヤ、ミンダナオという三つの大きな島嶼群で説明されます。",
    ],
    sources: [
      { label: "フィリピン最高裁判所・共和国法8491号", url: "https://elibrary.judiciary.gov.ph//thebookshelf//showdocs/2/4626" },
      { label: "フィリピン国家歴史委員会・国旗", url: "https://philhistoricsites.nhcp.gov.ph/registry_database/the-philippine-national-flag/" },
      { label: "ユネスコ・フィリピンの棚田群", url: "https://whc.unesco.org/en/list/722" },
    ],
    flag: { type: "horizontal", colors: ["#0038a8", "#ce1126", "#ffffff"] },
  },
  indonesia: {
    id: "indonesia",
    name: "Indonesia",
    nameJa: "インドネシア",
    shortName: "IDN",
    isoA3: "IDN",
    fragmentIds: ["indonesia"],
    isMajor: false,
    description: "A southern island group at the end of the front.",
    overview: "インドネシアは東南アジアの赤道付近に広がる群島国家です。スマトラ、ジャワ、カリマンタン、スラウェシ、パプアなどの大きな島と多数の島々からなります。",
    location: {
      region: "東南アジア・赤道周辺",
      description: "世界地図ではインド洋と太平洋の間に東西へ広がる島々として位置しています。",
    },
    flagOrigin: "インドネシアの国旗は、上が赤、下が白の二色旗です。政府ポータルでは『Merah Putih（赤と白）』と案内され、国旗の掲揚方法や色の扱いが法令で定められています。",
    trivia: [
      "インドネシアのバティックは、ユネスコ無形文化遺産に登録されています。",
      "インドネシアは多数の島からなる群島国家です。",
    ],
    sources: [
      { label: "インドネシア政府・国旗の掲揚方法", url: "https://indonesia.go.id/kategori/kependudukan/9784/panduan-dan-tata-cara-mengibarkan-sang-saka-merah-putih?lang=1" },
      { label: "インドネシア政府観光局・群島", url: "https://www.indonesia.travel/gb/en/cruise" },
      { label: "ユネスコ・インドネシアのバティック", url: "https://ich.unesco.org/en/RL/indonesian-batik-00170?RL=00170" },
    ],
    flag: { type: "horizontal", colors: ["#ce1126", "#ffffff"] },
  },
};
