export const FACTIONS = {
  blue: {
    id: "blue",
    name: "White Union",
    unitSprite: "./assets/units/player-red-circle.png",
    unitStyle: "visor",
    panelClass: "blue",
    statusText: "White Unionの支配領域",
    threatText: "安定",
    palette: {
      territory: "#f7f9fb",
      territoryDark: "#d4dce7",
      territoryBorder: "#aebdce",
      territoryLabel: "#6e7c91",
      unit: "#f2f5f8",
      accent: "#263751",
      flag: "#d94f58",
      occupation: "#2c5a9f",
    },
  },
  red: {
    id: "red",
    name: "赤勢力",
    unitSprite: "./assets/units/enemy-china.png",
    unitStyle: "cap",
    panelClass: "red",
    statusText: "敵対勢力が展開中",
    threatText: "高",
    palette: {
      territory: "#e15a5b",
      territoryDark: "#b93d4b",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "rgba(255,255,255,0.7)",
      unit: "#d53646",
      accent: "#ffe0d8",
      flag: "#c84349",
      occupation: "#c34e58",
    },
  },
  neutral: {
    id: "neutral",
    name: "中立勢力",
    unitSprite: "./assets/units/enemy-korea.png",
    unitStyle: "plain",
    panelClass: "neutral",
    statusText: "勢力未確定の中立地域",
    threatText: "警戒",
    palette: {
      territory: "#c9d1dd",
      territoryDark: "#9eaabd",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "#6e7c91",
      unit: "#eef2f6",
      accent: "#7b8798",
      flag: "#8b98aa",
      occupation: "#7b8798",
    },
  },
  pink: {
    id: "pink",
    name: "桃勢力",
    unitSprite: "./assets/units/enemy-north-korea.png",
    unitStyle: "plain",
    panelClass: "neutral",
    statusText: "勢力未確定の中立地域",
    threatText: "警戒",
    palette: {
      territory: "#f2b6ba",
      territoryDark: "#d78891",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "rgba(255,255,255,0.7)",
      unit: "#f3f1eb",
      accent: "#df4754",
      flag: "#e0737b",
      occupation: "#c34e58",
    },
  },
};
