export const FACTIONS = {
  blue: {
    id: "blue",
    isEnemy: false,
    name: "White Union",
    panelClass: "blue",
    statusText: "White Unionの支配領域",
    threatText: "安定",
    palette: {
      territory: "#f7f9fb",
      territoryDark: "#d4dce7",
      territoryBorder: "#aebdce",
      territoryLabel: "#6e7c91",
      accent: "#263751",
      occupation: "#2c5a9f",
    },
  },
  red: {
    id: "red",
    isEnemy: true,
    name: "赤勢力",
    panelClass: "red",
    statusText: "敵対勢力が展開中",
    threatText: "高",
    palette: {
      territory: "#e15a5b",
      territoryDark: "#b93d4b",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "rgba(255,255,255,0.7)",
      accent: "#ffe0d8",
      occupation: "#c34e58",
    },
  },
  gray: {
    id: "gray",
    isEnemy: true,
    name: "Gray Coalition",
    panelClass: "gray",
    statusText: "灰色連合の敵拠点",
    threatText: "警戒",
    palette: {
      territory: "#c9d1dd",
      territoryDark: "#9eaabd",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "#6e7c91",
      accent: "#7b8798",
      occupation: "#7b8798",
    },
  },
  pink: {
    id: "pink",
    isEnemy: true,
    name: "桃勢力",
    panelClass: "pink",
    statusText: "桃色連合の敵拠点",
    threatText: "警戒",
    palette: {
      territory: "#f2b6ba",
      territoryDark: "#d78891",
      territoryBorder: "rgba(255, 255, 255, 0.9)",
      territoryLabel: "rgba(255,255,255,0.7)",
      accent: "#df4754",
      occupation: "#c34e58",
    },
  },
};
